blog/urls.py
from django.conf.urls import include, url
from . import views
from .feeds import LatestPostsFeed

urlpatterns = [
	url(r'^$', views.post_list, name='post_list'),
	#url(r'^$', views.PostListView.as_view(), name='post_list'),
	url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
        r'(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
	url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
	url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
		]

mysite2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blog import urls
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls',
    			    namespace = 'blog',
    				app_name = 'blog')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from django.core.urlresolvers import reverse

from taggit.managers import TaggableManager
class Post(models.Model):
	STATUS_CHOICES = (
			('draft', 'Draft'),
			('published', 'Published'),
		)
	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, unique_for_date='publish')
	author = models.ForeignKey(User, related_name='blog_posts')
	body = models.TextField()
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	update = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10,
								   choices=STATUS_CHOICES,
								   default = 'draft')
	tags = TaggableManager()
	class Meta:
		ordering = ('-publish',)

	def __str__(self):
		return self.title
	def get_absolute_url(self):
		return reverse('blog:post_detail',
						args=[self.publish.year,
							  self.publish.strftime('%m'),
							  self.publish.strftime('%d'),
							  self.slug])

class Comment(models.Model):
	post = models.ForeignKey(Post, related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('created',)

	def __str__(self):
		return 'Комментарий от {} на {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
	#The first field rendered <input type="text">HTML element
	name = forms.CharField(max_length=25) 
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name', 'email', 'body')
		

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, \
								PageNotAnInteger

from django.views.generic import ListView

from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail

from taggit.models import Tag

def post_list(request):
	posts = Post.objects.filter(status='published')
	return render(request,
					'post/list.html',
					{'posts': posts})
def post_detail(request, year, month, day, post):
	post = get_object_or_404(Post, slug=post,
								   status='published',
								   publish__year=year,
								   publish__month=month,
								   publish__day=day)
	comments = post.comments.filter(active=True)
	if request.method == 'POST':
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=False)
			new_comment.post = post
			new_comment.save()
	else:
		comment_form = CommentForm()		
	return render(request, 'post/detail.html', {'post': post,
												'comments': comments,
												'comment_form': comment_form})

def post_list(request, tag_slug=None):
	object_list = Post.objects.filter(status="published")
	tag = None
	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug)
		object_list = object_list.filter(tags__in=[tag])

	paginator = Paginator(object_list, 3)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)
	return render(request, 'post/list.html', {'page': page,
											  'posts': posts,
											  'tag': tag})

class PostListView(ListView):
	queryset = Post.objects.filter(status='published')
	context_object_name = 'posts'
	paginate_by = 3
	template_name = 'post/list.html'	

def post_share(request, post_id):
	post = get_object_or_404(Post, id=post_id, status='published')
	sent = False
	if request.method == 'POST':
		form = EmailPostForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			post_url = request.build_absolute_uri(
								post.get_absolute_url())
			subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title) 
			message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
			send_mail(subject, message, 'agent53347@mail.ru', [cd['to']])
			sent = True
	else:
		form = EmailPostForm()
	return render(request, 'post/share.html', {'post': post,
											  'form': form,
											  'sent': sent})

blog/templates/base.html
{% load blog_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<href="{% static "css/blog.css" %}" link rel="stylesheet">
	<style type="text/css">
		#header{
			width: 100%;
			height: 100px;
			background-color: grey;
			font-family: sans-serif;
			display: block;

		}
		.main{
			float: right;
			margin-right: 50px;
		}
		.main li{
			display: inline;
			margin-left: 20px;
		}
		.main a {
			color: white;
			text-decoration: none;
		}
		.logo{
			position: relative;
			top: 30px;
			font-weight: 15px;
			left: 100px;
		}
		#content{
			padding: 15px;
			width: 65%;
			border-bottom: 1px solid black;
			margin-top: 10px;
			display: block;
		}
		#sidebar{
			width: 30%;
			background-color: pink;
			float: right;
			padding: 15px;
		}
		footer{
			display: block;
			width: 100%;
			height: 200px;
			background-color: #325862;
			padding: 20px;
		}
		.p{
			color: green;
		}
	</style>
</head>
<body>
	<div id="header">
		<div class="logo">
			Проект Наряд	
		</div>
		<ul class="main"> 
			<a href=""><li>Блог</li></a>
			<a href=""><li>Работа</li></a>
			<a href=""><li>Любовь</li></a>
			<a href=""><li>О нас</li></a>

		</ul>
	</div>
	<div id="sidebar">
		<h2>Мой блог</h2>
		<p>Это мой блог.=) Здесь опубликовано <h2 class="p">{% total_posts %}</h2> постов.</p>
		<p><a href="{% url 'blog:post_feed' %}">Нажми для получения моего RSS feed</a></p>
		<h3>Последние посты</h3>
		{% show_latest_posts 3 %}
		<h3>Самые популярные посты</h3>
		{% get_most_commented_posts as most_commented_posts %}
		<ul>
			{% for post in most_commented_posts %}
				<li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
			{% endfor %}
		</ul>
	</div>
	<div id="content">
		{% block content %}
		{% endblock %}	
	</div>
	<footer>
		Подвал
	</footer>
</body>
</html>

blog/templates/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
		<a href="?page={{ page.previous_page_number }}">Предыдущая</a>
		{% endif %}
		<span class="current">
			Страница {{ page.number }} из {{ page.paginator.num_pages }}.
		</span>
		{% if page.has_next %}
			<a href="?page={{ page.next_page_number }}">Следующая</a>
		{% endif %}
	</span>
	
</div>

blog/templates/post/detail.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block title %}{{post.title}}{% endblock %}
{% block content %}
	<h1>{{post.title}}</h1>
	<p class="date">
		Публикация {{post.publish}} от {{post.author}}
	</p>
	{{post.body|markdown}}
	<p style="color:red;">{{Post.id}}</p>
	<p>
		<a href="{% url "blog:post_share" post.id %}">
			Понравилась статья?Отправье на майл!
		</a>
	</p>
	{% with comments.count as total_comments %}
	<h2>
		{{ total_comments }} comment{{ total_comments|pluralize }}
	</h2>
	{% endwith %}
	{% for comment in comments %}
		<div class="comment">
			<p class="info">
				Комментарий {{ forloop.counter }} от {{ comment.name }}
				{{ comment.created }}
			</p>
			{{ comment.body|linebreaks }}
		</div>
	{% empty %}
		<p>Еще нет комментариев</p>
	{% endfor %}
	{% if new_comment %}
		<h2>Комментарий успешно добавлен!</h2>
	{% else %}
		<h2>Добавить новый комментарий</h2>
		<form action="." method="post">
			{{ comment_form.as_p }}
			{% csrf_token %}
			<p><input type="submit" value="Добавить"></p>
		</form>
			
	{% endif %}
{% endblock %}

blog/templates/post/latest_posts.html
<ul>
	{% for post in latest_posts %}
		<li>
			<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		</li>
	{% endfor %}
</ul>

blog/templates/post/list.html
{% extends "base.html" %}
{%  load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
	<h1>Мой блог</h1>
	{% if tag %}
		<h2>Статьи по тегу: {{ tag.name }} </h2>
	{% endif %}
	{% for post in posts %}
	<h2>
		<a href="{{ post.get_absolute_url }}">
		{{ post.title }}
		</a>
	</h2>
	<p class="tags">Тэги: {{ post.tags.all|join:", " }}
	<p>Все Теги:</p>
	{% for tag in post.tags.all %}
	<a href="{% url 'blog:post_list_by_tag' tag.slug %}">
		{{ tag.name }}
	</a>
	{% if not forloop.last %}, {% endif %}
	{% endfor %}	
	</p>
		
	<p class="date">
		Опубликовано {{ post.publish }}. Автор: {{ post.author }}
	</p>
	{{ post.body|markdown|truncatewords_html:30 }}
	{% endfor %}
	{% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/post/share.html
{% extends "base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
	{% if sent %}
		<h1>Сообщение успешно отправлено на майл</h1>
		<p>
			"{{ post.title }}" - Успешно отправлено на {{ cd.to }}
		</p>
	{% else %}
	<h1>Отправка "{{ post.title }}" на e-mail</h1>
	<form action="." method="post">
		{{ form.as_p }}
		{% csrf_token %}
		<input type="submit" value="Sebd e-mail">
	</form>
	{% endif %}
{% endblock %}